env:
  reveals:
    elastic:
      scheme: http
      host: ob-erasmus-reveals-dev-elastic.sysadmin.garden
      jsonApiPort: 9200
      index: aws-dev-reveals-data
    mail:
      fromAddress: 'Reveals'
      fromDescription: ''
      fromEmail: reveals.project.cz@gmail.com
      password: xgpnlbopbaevzmiz
      #SMTP host
      smtp:
        host: smtp.gmail.com
        # TLS Port 587 / SSL Port 465
        port: 465
        # enable authentication
        auth: true
        starttls:
          # enable TLS
          enable: true
        socketFactory:
          # SSL Factory Class
          clazz: javax.net.ssl.SSLSocketFactory