management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    build:
      enabled: true
    env:
      enabled: true

#server:
#  servlet:
#    context-path: /

cognizone:
  vinz:
    routes:
      - name: elastic
        path: ${cognizone.proxy.url}
        url: ${env.reveals.elastic.scheme}://${env.reveals.elastic.host}:${env.reveals.elastic.jsonApiPort}/
  proxy:
    url: /ob-erasmus-reveals-elastic-proxy
  elastic:
    url: ${env.reveals.elastic.url}
    index: ${env.reveals.elastic.index}
