management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    build:
      enabled: true
    env:
      enabled: true

#server:
#  servlet:
#    context-path: /

cognizone:
  proxy:
    url: /ob-erasmus-reveals-elastic-proxy
  elastic:
    index:
      name: ${env.reveals.elastic.index.name}
      url: ${env.reveals.elastic.index.url}
