logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

env:
  name: local
  reveals:
    elastic:
      scheme: http
      host: localhost
      jsonApiPort: 9200
      index: reveals-data
    mail:
      fromAddress: 'Reveals'
      fromDescription: ''
      fromEmail: reveals.project.cz@gmail.com
      password: xgpnlbopbaevzmiz
      #SMTP host
      smtp:
        host: smtp.gmail.com
        port: 465
        auth: true
        starttls:
          enable: true
        socketFactory:
          clazz: javax.net.ssl.SSLSocketFactory