env:
  reveals:
    elastic:
      scheme: http
      host: ob-erasmus-reveals-dev-elastic.cz-aws.net
      jsonApiPort: 9200
      index: aws-dev-reveals-data
    server:
      scheme: https
      host: ob-erasmus-reveals-dev.cogni.zone